server:
    port: 8080

spring:
    application:
        name: springbootstart

    datasource:
        url: jdbc:mysql://localhost:3306/startDB?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: kyungmin_root
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        open-in-view: false
